version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: jobsearch-postgres
    environment:
      - .env.utf8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
