# Generated by Django 5.0.1 on 2025-03-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_email_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resume",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Резюме",
                "verbose_name_plural": "Резюме",
            },
        ),
        migrations.AddField(
            model_name="resume",
            name="desired_position",
            field=models.CharField(
                default=1, max_length=200, verbose_name="Желаемая должность"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="languages",
            field=models.JSONField(default=list, verbose_name="Языки"),
        ),
        migrations.AddField(
            model_name="resume",
            name="preferred_employment",
            field=models.CharField(
                choices=[
                    ("full_time", "Полная занятость"),
                    ("part_time", "Частичная занятость"),
                    ("remote", "Удаленная работа"),
                    ("contract", "Контракт"),
                ],
                default="full_time",
                max_length=20,
                verbose_name="Предпочитаемый тип занятости",
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="salary_expectation",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Ожидаемая зарплата"
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="professional_summary",
            field=models.TextField(verbose_name="Профессиональное резюме"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="skills",
            field=models.JSONField(default=list, verbose_name="Навыки"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название резюме"),
        ),
    ]
