# Generated by Django 5.0.1 on 2025-05-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_resume_options_resume_desired_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="resume_file",
            field=models.FileField(
                blank=True, null=True, upload_to="resumes/", verbose_name="PDF резюме"
            ),
        ),
    ] 