# Generated by Django 5.0.1 on 2025-05-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_resume_resume_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
